import {
  addMark,
  type BaseEditor,
  deleteFragment,
  type Editor,
  extendEditor,
  getDirtyPaths,
  getFragment,
  insertBreak,
  insertFragment,
  insertNode,
  insertSoftBreak,
  insertText,
  normalizeNode,
  removeMark,
  setBlock,
  shouldNormalize,
  toggleAlignment,
  toggleBlock,
  toggleList,
  toggleMark,
} from './'
import { apply } from './core'
import {
  applyOperations,
  getChildren,
  getLastCommit,
  getLiveSelection,
  getOperationDirtiness,
  getOperations,
  getPathByRuntimeId,
  getRuntimeId,
  getSnapshot,
  initializePublicState,
  readEditor,
  replaceSnapshot,
  setBaseApply,
  subscribe,
  updateEditor,
  withTransaction,
} from './core/public-state'
import {
  above,
  after,
  before,
  bookmark,
  deleteBackward,
  deleteForward,
  edges,
  elementReadOnly,
  end,
  first,
  fragment,
  getVoid,
  hasBlocks,
  hasInlines,
  hasPath,
  hasTexts,
  isBlock,
  isEdge,
  isEmpty,
  isEnd,
  isNormalizing,
  isStart,
  last,
  leaf,
  levels,
  marks,
  next,
  node,
  nodes,
  normalize,
  parent,
  path,
  pathRef,
  pathRefs,
  point,
  pointRef,
  pointRefs,
  positions,
  previous,
  projectRange,
  range,
  rangeRef,
  rangeRefs,
  setNormalizing,
  shouldMergeNodesRemovePrevNode,
  start,
  string,
  unhangRange,
  withoutNormalizing,
} from './editor'
import type { Value } from './interfaces'
import {
  insertNodes,
  liftNodes,
  mergeNodes,
  moveNodes,
  removeNodes,
  setNodes,
  splitNodes,
  unsetNodes,
  unwrapNodes,
  wrapNodes,
} from './transforms-node'
import {
  collapse,
  deselect,
  move,
  select,
  setPoint,
  setSelection,
} from './transforms-selection'
import { deleteText } from './transforms-text'

/**
 * Create a new Slate `Editor` object.
 */
export const createEditor = <V extends Value = Value>(): Editor<V> => {
  let editor!: Editor<V>
  const runtimeEditor = () => editor as Editor<any>

  const baseEditor: BaseEditor<any> = {
    isElementReadOnly: () => false,
    isInline: (element) => (element as { type?: unknown }).type === 'link',
    isSelectable: () => true,
    isVoid: () => false,
    markableVoid: () => false,

    // Core
    applyOperations: (...args) => applyOperations(editor, ...args),

    // Editor
    addMark: (...args) => addMark(editor, ...args),
    bookmark: (...args) => bookmark(editor, ...args),
    deleteBackward: (...args) => deleteBackward(editor, ...args),
    deleteForward: (...args) => deleteForward(editor, ...args),
    deleteFragment: (...args) => deleteFragment(editor, ...args),
    getChildren: (...args) => getChildren(editor, ...args),
    getFragment: (...args) => getFragment(editor, ...args),
    getLastCommit: (...args) => getLastCommit(editor, ...args),
    getOperationDirtiness: (...args) => getOperationDirtiness(editor, ...args),
    getOperations: (...args) => getOperations(editor, ...args),
    getPathByRuntimeId: (...args) => getPathByRuntimeId(editor, ...args),
    getRuntimeId: (...args) => getRuntimeId(editor, ...args),
    read: (...args) => readEditor(editor, ...args),
    getSelection: (...args) => getLiveSelection(editor, ...args),
    getSnapshot: (...args) => getSnapshot(editor, ...args),
    insertBreak: (...args) => insertBreak(editor, ...args),
    insertSoftBreak: (...args) => insertSoftBreak(editor, ...args),
    insertFragment: (...args) => insertFragment(runtimeEditor(), ...args),
    insertNode: (...args) => insertNode(runtimeEditor(), ...args),
    insertText: (...args) => insertText(editor, ...args),
    normalizeNode: (...args) => normalizeNode(editor, ...args),
    removeMark: (...args) => removeMark(editor, ...args),
    setBlock: (...args) => setBlock(editor, ...args),
    toggleAlignment: (...args) => toggleAlignment(editor, ...args),
    toggleBlock: (...args) => toggleBlock(editor, ...args),
    toggleList: (...args) => toggleList(editor, ...args),
    toggleMark: (...args) => toggleMark(editor, ...args),
    getDirtyPaths: (...args) => getDirtyPaths(editor, ...args),
    shouldNormalize: (...args) => shouldNormalize(editor, ...args),

    // Editor interface
    above: (...args) => above(editor, ...args),
    after: (...args) => after(editor, ...args),
    before: (...args) => before(editor, ...args),
    collapse: (...args) => collapse(editor, ...args),
    delete: (...args) => deleteText(runtimeEditor(), ...args),
    deselect: (...args) => deselect(editor, ...args),
    edges: (...args) => edges(editor, ...args),
    elementReadOnly: (...args) => elementReadOnly(editor, ...args),
    end: (...args) => end(editor, ...args),
    first: (...args) => first(editor, ...args),
    fragment: (...args) => fragment(editor, ...args),
    getMarks: (...args) => marks(editor, ...args),
    hasBlocks: (...args) => hasBlocks(editor, ...args),
    hasInlines: (...args) => hasInlines(editor, ...args),
    hasPath: (...args) => hasPath(editor, ...args),
    hasTexts: (...args) => hasTexts(editor, ...args),
    insertNodes: (...args) => insertNodes(runtimeEditor(), ...args),
    isBlock: (...args) => isBlock(editor, ...args),
    isEdge: (...args) => isEdge(editor, ...args),
    isEmpty: (...args) => isEmpty(editor, ...args),
    isEnd: (...args) => isEnd(editor, ...args),
    isNormalizing: (...args) => isNormalizing(editor, ...args),
    isStart: (...args) => isStart(editor, ...args),
    last: (...args) => last(editor, ...args),
    leaf: (...args) => leaf(editor, ...args),
    levels: (...args) => levels(editor, ...args),
    liftNodes: (...args) => liftNodes(runtimeEditor(), ...args),
    mergeNodes: (...args) => mergeNodes(runtimeEditor(), ...args),
    move: (...args) => move(editor, ...args),
    moveNodes: (...args) => moveNodes(runtimeEditor(), ...args),
    next: (...args) => next(editor, ...args),
    node: (...args) => node(editor, ...args),
    nodes: (...args) => nodes(editor, ...args),
    normalize: (...args) => normalize(editor, ...args),
    parent: (...args) => parent(editor, ...args),
    path: (...args) => path(editor, ...args),
    pathRef: (...args) => pathRef(editor, ...args),
    pathRefs: (...args) => pathRefs(editor, ...args),
    point: (...args) => point(editor, ...args),
    pointRef: (...args) => pointRef(editor, ...args),
    pointRefs: (...args) => pointRefs(editor, ...args),
    positions: (...args) => positions(editor, ...args),
    previous: (...args) => previous(editor, ...args),
    projectRange: (...args) => projectRange(editor, ...args),
    range: (...args) => range(editor, ...args),
    rangeRef: (...args) => rangeRef(editor, ...args),
    rangeRefs: (...args) => rangeRefs(editor, ...args),
    removeNodes: (...args) => removeNodes(runtimeEditor(), ...args),
    select: (...args) => select(editor, ...args),
    replace: (...args) => replaceSnapshot(editor, ...args),
    reset: (...args) => replaceSnapshot(editor, ...args),
    setNodes: (...args) => setNodes(runtimeEditor(), ...args),
    setNormalizing: (...args) => setNormalizing(editor, ...args),
    setPoint: (...args) => setPoint(editor, ...args),
    setSelection: (...args) => setSelection(editor, ...args),
    splitNodes: (...args) => splitNodes(runtimeEditor(), ...args),
    start: (...args) => start(editor, ...args),
    string: (...args) => string(editor, ...args),
    subscribe: (...args) => subscribe(editor, ...args),
    update: (...args) => updateEditor(editor, ...args),
    extend: (...args) => extendEditor(editor, ...args),
    unhangRange: (...args) => unhangRange(editor, ...args),
    unsetNodes: (...args) => unsetNodes(runtimeEditor(), ...args),
    unwrapNodes: (...args) => unwrapNodes(runtimeEditor(), ...args),
    void: (...args) => getVoid(editor, ...args),
    withoutNormalizing: (...args) => withoutNormalizing(editor, ...args),
    withTransaction: (fn) =>
      withTransaction(editor, fn, { authority: 'explicit' }),
    wrapNodes: (...args) => wrapNodes(runtimeEditor(), ...args),
    shouldMergeNodesRemovePrevNode: (...args) =>
      shouldMergeNodesRemovePrevNode(editor, ...args),
  }

  editor = baseEditor as Editor<V>

  setBaseApply(editor, (...args) => apply(editor, ...args))

  initializePublicState(editor)

  return editor
}
